# Generated by Django 4.2.5 on 2023-10-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0002_rename_message_message_body_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='is_deleted_by_sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='receivers',
            name='is_deleted',
        ),
    ]
