# Generated by Django 4.2.5 on 2023-10-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0003_rename_is_deleted_message_is_deleted_by_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted_by_sender',
        ),
    ]
