# Generated by Django 4.2.5 on 2023-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0004_remove_message_is_deleted_by_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
